services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: django_base
      POSTGRES_USER: django_base
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - staticfiles:/app/staticfiles

volumes:
  pgdata:
  staticfiles: